### 회원가입
POST http://localhost:10000/auth/signup
Content-Type: application/json

{
  "email": "poko@naver.com",
  "password": "Pok123123123!",
  "name": "poko",
  "phone": "01012311234",
  "profileImage": "",
  "userRoleType": "ROLE_ADMIN"
}

### 로그인
POST http://localhost:10000/auth/login
Content-Type: application/json

{
  "email": "poko@naver.com",
  "password": "Pok123123123!"
}


> {%
    client.global.set("accessToken", response.body.data.issueToken.accessToken);
    client.global.set("refreshToken", response.body.data.issueToken.refreshToken);
%}


### 로그아웃
POST http://localhost:10000/auth/logout
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### 토큰 재발급
POST http://localhost:10000/auth/generate-token
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "refreshToken": "{{refreshToken}}"

}