### 회원가입
POST http://localhost:10000/api/v1/auth/signup
Content-Type: application/json

{
  "email": "poko@naver.com",
  "password": "Pok123123123!",
  "name": "poko",
  "phone": "01012311234",
  "profileImage": "",
  "userRoleType": "ROLE_ADMIN"
}

> {%
    client.global.set("userId", response.body.data.newUser.userId);
    client.global.set("userRoleType", response.body.data.newUser.userRoleType);
%}

### 로그인
POST http://localhost:10000/api/v1/auth/login
Content-Type: application/json

{
  "email": "poko@naver.com",
  "password": "Pok123123123!"
}


> {%
    client.global.set("accessToken", response.body.data.issueToken.accessToken);
    client.global.set("refreshToken", response.body.data.issueToken.refreshToken);
%}


### 로그아웃
POST http://localhost:10000/api/v1/auth/logout
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### 토큰 재발급
POST http://localhost:10000/api/v1/auth/generate-token
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "refreshToken": "{{refreshToken}}"

}


### 나의 프로필 조회
GET http://localhost:10000/api/v1/users/profile
Content-Type: application/json
X-User-Id: {{userId}}
X-User-Role: {{userRoleType}}


### 동적 회원 조회
GET http://localhost:10000/api/v1/users?id=100&email=test@example.com&name=홍길동&phone=01012345678&userRoleType=ROLE_ADMIN&isDeleted=false&createdBy=1&createdFrom=2024-01-01T00:00:00&createdTo=2025-01-01T00:00:00&modifiedBy=2&modifiedFrom=2024-06-01T00:00:00&modifiedTo=2025-01-01T00:00:00&deletedBy=3&deletedFrom=2024-12-01T00:00:00&deletedTo=2025-01-01T00:00:00&page=0&size=20&sort=createdAt,desc
Content-Type: application/json
X-User-Id: {{userId}}
X-User-Role: {{userRoleType}}

### 동적 회원 조회
GET http://localhost:10000/api/v1/users?id=1
Content-Type: application/json
X-User-Id: {{userId}}
X-User-Role: {{userRoleType}}
